In [1]:
import pandas  as pd
import numpy as np
import tensorflow as tf

In [98]:
from sklearn.preprocessing import Imputer

In [247]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale

In [17]:
####hourly data
ae_index = pd.read_excel('3 AE_index_20.xls')
ap_index = pd.read_excel('3 ap_index_20.xls')
dst_index = pd.read_excel('3 DST_index_20.xls')
kp_index = pd.read_excel('3 kp_index_20.xls')

####daily data
f_value = pd.read_excel('3 f 10.7cm-20.xls')
ssn = pd.read_excel('3 SSN-20.xls')

In [18]:
fof2 = pd.read_excel('3 Can_foF2Data_20.xls')

In [19]:
ae_index.tail()

DOY    0    1    2    3    4    5    6    7    8 ...    14    15  \
19751227  361  166  183   80  197  276  411  410  647  327 ...   292  1112   
19751228  362  544  322  141  172  220  227  135   88   89 ...    47    51   
19751229  363  275  198   82  142  176  361  360  299  385 ...   119    92   
19751230  364  169  246  174  224  305  223  112  125  177 ...   132    73   
19751231  365   42   51  113  162   37   32   51  104   36 ...    99    78   

            16   17   18   19   20   21   22   23  
19751227  1179  813  677  720  671  473  435  341  
19751228    92  333  138  111   95  101  371  157  
19751229   338  161  345  525  172  202   85   85  
19751230    85  108   71  128  239  107   83  124  
19751231   103   53   54   47   37   41   63   42  

[5 rows x 25 columns]

In [20]:
ae_index = ae_index.drop('DOY', axis = 1)
ap_index = ap_index.drop('DOY', axis = 1)
dst_index = dst_index.drop('DOY', axis = 1)
kp_index = kp_index.drop('DOY', axis = 1)

In [76]:
fof2 = fof2.drop('DOY', axis = 1)

In [112]:
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
mean_imputer = imp.fit(f_value)
names = f_value.columns.values
f_value = pd.DataFrame(mean_imputer.transform(f_value))
f_value.columns = names

In [35]:
ae_indices = []
for i in ae_index.index.values:
    for j in range(24):
        ae_indices.append(str(i)+'_'+str(j))

In [36]:
ae_index_1 = pd.DataFrame([ae_indices,ae_index.values.flatten().tolist()]).T

In [51]:
ae_index_1.columns = ['Time', 'ae_value']

In [52]:
ap_indices = []
for i in ap_index.index.values:
    for j in range(24):
        ap_indices.append(str(i)+'_'+str(j))
        

ap_index_1 = pd.DataFrame([ap_indices,ap_index.values.flatten().tolist()]).T

ap_index_1.columns = ['Time', 'ap_value']

In [53]:
dst_indices = []
for i in dst_index.index.values:
    for j in range(24):
        dst_indices.append(str(i)+'_'+str(j))
        

dst_index_1 = pd.DataFrame([dst_indices,dst_index.values.flatten().tolist()]).T

dst_index_1.columns = ['Time', 'dst_value']

In [79]:
kp_indices = []
for i in kp_index.index.values:
    for j in range(24):
        kp_indices.append(str(i)+'_'+str(j))
        

kp_index_1 = pd.DataFrame([kp_indices,kp_index.values.flatten().tolist()]).T

kp_index_1.columns = ['Time', 'kp_value']

In [123]:
f_indices = []
for i in f_value.index.values:
    for j in range(24):
        f_indices.append((str(int(f_value['YEAR'][i]))+'_'+str(j), f_value['f10.7_index'][i]))

In [124]:
f_value_1 = pd.DataFrame(f_indices)

In [125]:
f_value_1.columns = ['Time', 'f_value']

In [66]:
ssn_indices = []
for i in ssn.index.values:
    for j in range(24):
        ssn_indices.append((str(ssn['year'][i])+'_'+str(j), ssn['R (Sunspot No.)'][i]))
        
ssn_1 = pd.DataFrame(ssn_indices)

ssn_1.columns = ['Time', 'ssn']

In [82]:
fof2_indices = []
for i in fof2.index.values:
    for j in range(24):
        fof2_indices.append(str(fof2['C-20'][i])+'_'+str(j))
        

fof2_1 = pd.DataFrame([fof2_indices,fof2.drop('C-20', axis = 1).values.flatten().tolist()]).T

fof2_1.columns = ['Time', 'fof2']

### Final Tables = ae_index_1, ap_index_1, kp_index_1, dst_index_1, f_value_1, ssn_1, fof2_1

In [129]:
data = pd.merge(ae_index_1, ap_index_1, how = 'inner', on = 'Time')
data = pd.merge(data, dst_index_1, how = 'inner', on = 'Time')
data = pd.merge(data, kp_index_1, how = 'inner', on = 'Time')
data = pd.merge(data, ssn_1, how = 'inner', on = 'Time')
data = pd.merge(data, f_value_1, how = 'inner', on = 'Time')
data = pd.merge(data, fof2_1, how = 'inner', on = 'Time')

In [130]:
data

Time ae_value ap_value dst_value kp_value  ssn  f_value fof2
0       19641001_0      339       22       -19       37   25     72.0  4.8
1       19641001_1      277       22       -14       37   25     72.0  5.2
2       19641001_2       57       22       -12       37   25     72.0  5.3
3       19641001_3       74       18       -12       33   25     72.0  5.5
4       19641001_4      285       18       -13       33   25     72.0  5.5
5       19641001_5      165       18       -13       33   25     72.0  4.5
6       19641001_6      113        9       -12       23   25     72.0    5
7       19641001_7      143        9       -11       23   25     72.0  4.9
8       19641001_8      265        9        -8       23   25     72.0  4.4
9       19641001_9      246        6        -8       17   25     72.0  4.3
10     19641001_10       92        6        -8       17   25     72.0  4.1
11     19641001_11      131        6       -10       17   25     72.0    4
12     19641001_12       96        6        -7       17   25     72.0  3.7
13     19641001_13       95        6        -8       17   25     72.0  3.4
14     19641001_14      238        6       -10       17   25     72.0  3.1
15     19641001_15      138        9       -13       23   25     72.0  2.9
16     19641001_16      220        9       -13       23   25     72.0  2.8
17     19641001_17      172        9        -9       23   25     72.0  2.9
18     19641001_18       70        2        -8        3   25     72.0  2.4
19     19641001_19       52        2        -8        3   25     72.0  2.5
20     19641001_20       30        2       -10        3   25     72.0  3.4
21     19641001_21       27        3        -9        7   25     72.0  4.5
22     19641001_22       29        3       -10        7   25     72.0  5.2
23     19641001_23       69        3       -13        7   25     72.0  5.2
24      19641002_0      173       12       -12       27   18     71.6  5.8
25      19641002_1      232       12       -10       27   18     71.6  5.9
26      19641002_2       79       12        -8       27   18     71.6  NaN
27      19641002_3       27        3        -5        7   18     71.6  NaN
28      19641002_4       19        3        -3        7   18     71.6  5.6
29      19641002_5       18        3        -2        7   18     71.6  5.5
...            ...      ...      ...       ...      ...  ...      ...  ...
98586  19751230_18       71       12       -13       27    0     71.9  2.7
98587  19751230_19      128       12       -15       27    0     71.9  3.1
98588  19751230_20      239       12       -15       27    0     71.9    4
98589  19751230_21      107        7       -11       20    0     71.9  4.6
98590  19751230_22       83        7       -12       20    0     71.9  4.1
98591  19751230_23      124        7       -15       20    0     71.9  4.4
98592   19751231_0       42       15       -16       30    0     72.1  4.5
98593   19751231_1       51       15       -13       30    0     72.1  5.1
98594   19751231_2      113       15       -12       30    0     72.1  5.5
98595   19751231_3      162       12       -10       27    0     72.1  5.1
98596   19751231_4       37       12        -9       27    0     72.1  5.1
98597   19751231_5       32       12        -8       27    0     72.1  5.1
98598   19751231_6       51        4        -9       10    0     72.1    5
98599   19751231_7      104        4        -7       10    0     72.1  5.6
98600   19751231_8       36        4        -7       10    0     72.1  5.8
98601   19751231_9       33        4        -6       10    0     72.1  NaN
98602  19751231_10       43        4        -6       10    0     72.1  5.5
98603  19751231_11      113        4        -6       10    0     72.1  4.6
98604  19751231_12      126        3        -6        7    0     72.1  4.6
98605  19751231_13      134        3        -9        7    0     72.1  4.5
98606  19751231_14       99        3        -9        7    0     72.1  4.6
98607  19751231_15       78        4   

In [137]:
test_data = data[data['fof2'].isnull()]

In [299]:
t_data = data[data['fof2'].isnull()==False].copy()

In [300]:
t_data.index = range(t_data.shape[0])
test_data.index = range(test_data.shape[0])

In [301]:
t_data.shape, test_data.shape

((91948, 8), (6668, 8))

In [304]:
t_data1 = pd.DataFrame(scale(t_data.drop(['Time','fof2'], axis = 1)))
t_data1['fof2'] = t_data['fof2']
t_data = t_data1

In [309]:
train_data, val_data = train_test_split(t_data, test_size = 0.2, random_state = 42)

In [310]:
train_data.shape

(73558, 7)

In [311]:
train_data.index = range(train_data.shape[0])
val_data.index = range(val_data.shape[0])
test_data.index = range(test_data.shape[0])

In [312]:
train_data.head()

0         1         2         3         4         5 fof2
0  0.916106  0.795916 -1.619500  1.314619  1.021167  0.393846  8.4
1 -0.837418 -0.602453  0.436806 -1.312253 -1.204221 -1.264410  5.1
2 -0.863205 -0.546518 -0.101750 -1.028267  0.779277  0.686987  5.3
3  0.127020 -0.322779 -0.199669 -0.105312 -0.607559 -0.419475    7
4 -0.703325 -0.490583  0.877443 -0.815277 -1.091339 -1.051740  3.5

In [313]:
train_X = train_data.drop(['fof2'],axis = 1)
train_Y = train_data['fof2']
val_X = val_data.drop(['fof2'],axis = 1)
val_Y = val_data['fof2']

## Simple Feed-Forward Neural Network

In [402]:
## Hyper-parameters

n_hidden_1 = 32
n_hidden_2 = 16
n_hidden_3 = 8
n_epochs = 50
batch_size = 128
n_batch = int(train_data.shape[0]/batch_size) + 1

In [403]:
tf.reset_default_graph()

In [404]:
X = tf.placeholder(shape = [None, 6], dtype = tf.float32, name = 'input_X')
Y = tf.placeholder(shape = [None], dtype = tf.float32, name = 'output_y')

In [405]:
W1 = tf.get_variable('W1', shape = [6, n_hidden_1],
                    initializer = tf.contrib.layers.xavier_initializer())
W2 = tf.get_variable('W2', shape = [n_hidden_1, n_hidden_2],
                    initializer = tf.contrib.layers.xavier_initializer())
W3 = tf.get_variable('W3', shape = [n_hidden_2, n_hidden_3],
                    initializer = tf.contrib.layers.xavier_initializer())
W4 = tf.get_variable('W4', shape = [n_hidden_3, 1],
                    initializer = tf.contrib.layers.xavier_initializer())
B1 = tf.get_variable(name='B1', shape=[n_hidden_1], initializer=tf.zeros_initializer())
B2 = tf.get_variable(name='B2', shape=[n_hidden_2], initializer=tf.zeros_initializer())
B3 = tf.get_variable(name='B3', shape=[n_hidden_3], initializer=tf.zeros_initializer())
B4 = tf.get_variable(name='B4', shape=[1], initializer=tf.zeros_initializer())

In [406]:
def model(X):
    layer1 = tf.nn.tanh(tf.add(tf.matmul(X, W1), B1))
    layer2 = tf.nn.tanh(tf.add(tf.matmul(layer1,W2), B2))
    layer3 = (tf.add(tf.matmul(layer2,W3), B3))
    layer4 = tf.add(tf.matmul(layer3, W4), B4)
    return layer4

In [407]:
out = model(X)

In [408]:
loss = tf.reduce_mean(tf.square(out - Y))

In [409]:
op = tf.train.AdamOptimizer(0.1)
train_step = op.minimize(loss)

In [410]:
init = tf.global_variables_initializer()

In [411]:
sess = tf.Session()
sess.run(init)

In [412]:
for epoch in range(n_epochs):
    for i in range(n_batch):
        if i == n_batch - 1:
            batch_x = train_X[batch_size*i:]
            batch_y = train_Y[batch_size*i:]
        else:
            batch_x = train_X[batch_size*i: batch_size*(i+1)]
            batch_y = train_Y[batch_size*i: batch_size*(i+1)]
        
        feed_dict = {
            X: batch_x,
            Y: batch_y
        }
        sess.run(train_step, feed_dict = feed_dict)
    
    feed_dict = {
        X: train_X[0:10],
        Y: train_Y[0:10]
    }
    train_loss, pre = sess.run([loss, out], feed_dict = feed_dict)
    
    feed_dict = {
        X: val_X,
        Y: val_Y
    }
    test_loss = sess.run(loss, feed_dict = feed_dict)
    print('Epoch =', (epoch+1), 'val_loss =', test_loss, 'train_loss =',train_loss )
    print(pre)

Epoch = 1 val_loss = 4.179405 train_loss = 2.9738934
[[6.260898 ]
 [6.096891 ]
 [6.140788 ]
 [6.2139845]
 [6.096674 ]
 [6.2380075]
 [6.0870433]
 [6.0963497]
 [6.077402 ]
 [6.0734386]]
Epoch = 2 val_loss = 4.1996603 train_loss = 2.963067
[[6.046649 ]
 [6.303482 ]
 [6.2622185]
 [6.3102984]
 [6.31214  ]
 [6.079768 ]
 [6.2954273]
 [6.275175 ]
 [6.2662687]
 [6.2608576]]
Epoch = 3 val_loss = 4.1476083 train_loss = 3.0085657
[[5.958871 ]
 [6.1534886]
 [6.0299253]
 [6.142153 ]
 [6.1540833]
 [5.9685082]
 [6.0634623]
 [5.98457  ]
 [5.9858437]
 [5.965081 ]]
Epoch = 4 val_loss = 4.160518 train_loss = 2.9661245
[[6.0863805]
 [6.150638 ]
 [6.149506 ]
 [6.152346 ]
 [6.15139  ]
 [6.1090555]
 [6.1546965]
 [6.216746 ]
 [6.209978 ]
 [6.2239323]]
Epoch = 5 val_loss = 4.1446996 train_loss = 3.0995545
[[5.815869 ]
 [6.0515447]
 [5.788616 ]
 [6.0506287]
 [6.051506 ]
 [5.840479 ]
 [5.88103  ]
 [5.790166 ]
 [5.7931046]
 [5.881872 ]]
Epoch = 6 val_loss = 4.132255 train_loss = 3.0465739
[[5.856576 ]
 [5.9552   ]

Epoch = 46 val_loss = 4.1340375 train_loss = 3.1255758
[[5.8180704]
 [5.891139 ]
 [5.8711295]
 [5.911519 ]
 [5.891139 ]
 [5.8180704]
 [5.960487 ]
 [5.8620777]
 [5.7648706]
 [5.7278547]]
Epoch = 47 val_loss = 4.1293983 train_loss = 3.051336
[[6.006445 ]
 [5.995334 ]
 [5.9032474]
 [5.964033 ]
 [5.995334 ]
 [6.006441 ]
 [5.9754496]
 [5.874817 ]
 [5.931191 ]
 [5.874817 ]]
Epoch = 48 val_loss = 4.131523 train_loss = 3.073055
[[6.003201 ]
 [5.912868 ]
 [5.8766794]
 [5.921221 ]
 [5.9129024]
 [6.003201 ]
 [5.831009 ]
 [5.9186893]
 [5.8831835]
 [5.929151 ]]
Epoch = 49 val_loss = 4.1469116 train_loss = 3.0766354
[[5.8565636]
 [6.04903  ]
 [5.7354593]
 [6.07049  ]
 [6.0438056]
 [5.8565636]
 [6.048743 ]
 [5.7354593]
 [6.0126343]
 [5.923004 ]]
Epoch = 50 val_loss = 4.1333723 train_loss = 3.0231059
[[5.9253607]
 [6.0706053]
 [5.958553 ]
 [6.047115 ]
 [6.0706053]
 [5.942705 ]
 [6.0041676]
 [6.0163307]
 [6.01635  ]
 [5.973153 ]]


In [342]:
### Train Final Model

train_X1 = t_data.drop('fof2', axis = 1)
train_Y1 = t_data['fof2']

n_batch = int(train_X1.shape[0]/batch_size) + 1

sess.run(init)

for epoch in range(n_epochs):
    for i in range(n_batch):
        if i == n_batch - 1:
            batch_x = train_X1[batch_size*i:]
            batch_y = train_Y1[batch_size*i:]
        else:
            batch_x = train_X1[batch_size*i: batch_size*(i+1)]
            batch_y = train_Y1[batch_size*i: batch_size*(i+1)]
        
        feed_dict = {
            X: batch_x,
            Y: batch_y
        }
        sess.run(train_step, feed_dict = feed_dict)

In [344]:
#### Predict

test_data1 = pd.DataFrame(scale(test_data.drop(['Time', 'fof2'], axis = 1)))

feed_dict = {X: test_data1}
prediction = sess.run(out, feed_dict = feed_dict)

In [359]:
prediction.min(), prediction.max()

(4.7846093, 4.7846093)